name: Alfresco JODConverter CI

on:
  pull_request:
    branches:
      - master
      - feature/**
      - fix/**
  push:
    branches:
      - master
      - feature/**
      - fix/**
  workflow_dispatch:

env:
  GIT_USERNAME: ${{ secrets.BOT_GITHUB_USERNAME }}
  GIT_PASSWORD: ${{ secrets.BOT_GITHUB_TOKEN }}
  MAVEN_USERNAME: ${{ secrets.NEXUS_USERNAME }}
  MAVEN_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
  GITHUB_ACTIONS_DEPLOY_TIMEOUT: 40

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.34.2
      - name: "Build"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: mvn -f jodconverter-core/pom.xml -B -V install -U -DskipTests

  release:
    name: "Release"
    runs-on: ubuntu-latest
    needs: build
    if: >
      github.ref_name == 'master' &&
      github.event_name != 'pull_request' &&
      !contains(github.event.head_commit.message, '[no-release]')
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: Alfresco/alfresco-build-tools/.github/actions/get-build-info@v1.34.2
      - uses: Alfresco/alfresco-build-tools/.github/actions/setup-java-build@v1.34.2
      - uses: Alfresco/alfresco-build-tools/.github/actions/configure-git-author@v1.34.2
        with:
          username: ${{ secrets.BOT_GITHUB_USERNAME }}
          email: ${{ secrets.BOT_GITHUB_EMAIL }}
      - name: "Verify release tag"
        run: bash scripts/ci/verify_release_tag.sh
      - name: "Release"
        timeout-minutes: ${{ fromJSON(env.GITHUB_ACTIONS_DEPLOY_TIMEOUT) }}
        run: bash scripts/ci/maven_release.sh
